// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.1
// source: trim/trim.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Trim_TrimSpace_FullMethodName = "/proto.Trim/TrimSpace"
)

// TrimClient is the client API for Trim service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrimClient interface {
	TrimSpace(ctx context.Context, in *TrimRequest, opts ...grpc.CallOption) (*TrimResponse, error)
}

type trimClient struct {
	cc grpc.ClientConnInterface
}

func NewTrimClient(cc grpc.ClientConnInterface) TrimClient {
	return &trimClient{cc}
}

func (c *trimClient) TrimSpace(ctx context.Context, in *TrimRequest, opts ...grpc.CallOption) (*TrimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrimResponse)
	err := c.cc.Invoke(ctx, Trim_TrimSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrimServer is the server API for Trim service.
// All implementations must embed UnimplementedTrimServer
// for forward compatibility.
type TrimServer interface {
	TrimSpace(context.Context, *TrimRequest) (*TrimResponse, error)
	mustEmbedUnimplementedTrimServer()
}

// UnimplementedTrimServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrimServer struct{}

func (UnimplementedTrimServer) TrimSpace(context.Context, *TrimRequest) (*TrimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrimSpace not implemented")
}
func (UnimplementedTrimServer) mustEmbedUnimplementedTrimServer() {}
func (UnimplementedTrimServer) testEmbeddedByValue()              {}

// UnsafeTrimServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrimServer will
// result in compilation errors.
type UnsafeTrimServer interface {
	mustEmbedUnimplementedTrimServer()
}

func RegisterTrimServer(s grpc.ServiceRegistrar, srv TrimServer) {
	// If the following call pancis, it indicates UnimplementedTrimServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Trim_ServiceDesc, srv)
}

func _Trim_TrimSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrimServer).TrimSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Trim_TrimSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrimServer).TrimSpace(ctx, req.(*TrimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Trim_ServiceDesc is the grpc.ServiceDesc for Trim service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Trim_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Trim",
	HandlerType: (*TrimServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TrimSpace",
			Handler:    _Trim_TrimSpace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trim/trim.proto",
}

const (
	AddService_Sum_FullMethodName    = "/proto.AddService/Sum"
	AddService_Concat_FullMethodName = "/proto.AddService/Concat"
)

// AddServiceClient is the client API for AddService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddServiceClient interface {
	Sum(ctx context.Context, in *StrRequest, opts ...grpc.CallOption) (*StrResponse, error)
	Concat(ctx context.Context, in *StrRequest, opts ...grpc.CallOption) (*StrResponse, error)
}

type addServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddServiceClient(cc grpc.ClientConnInterface) AddServiceClient {
	return &addServiceClient{cc}
}

func (c *addServiceClient) Sum(ctx context.Context, in *StrRequest, opts ...grpc.CallOption) (*StrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrResponse)
	err := c.cc.Invoke(ctx, AddService_Sum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) Concat(ctx context.Context, in *StrRequest, opts ...grpc.CallOption) (*StrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrResponse)
	err := c.cc.Invoke(ctx, AddService_Concat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddServiceServer is the server API for AddService service.
// All implementations must embed UnimplementedAddServiceServer
// for forward compatibility.
type AddServiceServer interface {
	Sum(context.Context, *StrRequest) (*StrResponse, error)
	Concat(context.Context, *StrRequest) (*StrResponse, error)
	mustEmbedUnimplementedAddServiceServer()
}

// UnimplementedAddServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAddServiceServer struct{}

func (UnimplementedAddServiceServer) Sum(context.Context, *StrRequest) (*StrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedAddServiceServer) Concat(context.Context, *StrRequest) (*StrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Concat not implemented")
}
func (UnimplementedAddServiceServer) mustEmbedUnimplementedAddServiceServer() {}
func (UnimplementedAddServiceServer) testEmbeddedByValue()                    {}

// UnsafeAddServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddServiceServer will
// result in compilation errors.
type UnsafeAddServiceServer interface {
	mustEmbedUnimplementedAddServiceServer()
}

func RegisterAddServiceServer(s grpc.ServiceRegistrar, srv AddServiceServer) {
	// If the following call pancis, it indicates UnimplementedAddServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AddService_ServiceDesc, srv)
}

func _AddService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddService_Sum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).Sum(ctx, req.(*StrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_Concat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).Concat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddService_Concat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).Concat(ctx, req.(*StrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AddService_ServiceDesc is the grpc.ServiceDesc for AddService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AddService",
	HandlerType: (*AddServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _AddService_Sum_Handler,
		},
		{
			MethodName: "Concat",
			Handler:    _AddService_Concat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trim/trim.proto",
}
