// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.1
// source: trim/trim.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Trim方法的请求参数
type TrimRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S string `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *TrimRequest) Reset() {
	*x = TrimRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trim_trim_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimRequest) ProtoMessage() {}

func (x *TrimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trim_trim_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimRequest.ProtoReflect.Descriptor instead.
func (*TrimRequest) Descriptor() ([]byte, []int) {
	return file_trim_trim_proto_rawDescGZIP(), []int{0}
}

func (x *TrimRequest) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

// Trim方法的响应
type TrimResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S string `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *TrimResponse) Reset() {
	*x = TrimResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trim_trim_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimResponse) ProtoMessage() {}

func (x *TrimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trim_trim_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimResponse.ProtoReflect.Descriptor instead.
func (*TrimResponse) Descriptor() ([]byte, []int) {
	return file_trim_trim_proto_rawDescGZIP(), []int{1}
}

func (x *TrimResponse) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

// Sum和Concat的请求和响应
type StrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B string `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *StrRequest) Reset() {
	*x = StrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trim_trim_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrRequest) ProtoMessage() {}

func (x *StrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trim_trim_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrRequest.ProtoReflect.Descriptor instead.
func (*StrRequest) Descriptor() ([]byte, []int) {
	return file_trim_trim_proto_rawDescGZIP(), []int{2}
}

func (x *StrRequest) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *StrRequest) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

type StrResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R string `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
}

func (x *StrResponse) Reset() {
	*x = StrResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trim_trim_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrResponse) ProtoMessage() {}

func (x *StrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trim_trim_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrResponse.ProtoReflect.Descriptor instead.
func (*StrResponse) Descriptor() ([]byte, []int) {
	return file_trim_trim_proto_rawDescGZIP(), []int{3}
}

func (x *StrResponse) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

var File_trim_trim_proto protoreflect.FileDescriptor

var file_trim_trim_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x72, 0x69, 0x6d, 0x2f, 0x74, 0x72, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x0b, 0x54, 0x72, 0x69, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0x1c, 0x0a, 0x0c, 0x54, 0x72, 0x69, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x01, 0x73, 0x22, 0x28, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x61, 0x12,
	0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x62, 0x22, 0x1b, 0x0a,
	0x0b, 0x53, 0x74, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0c, 0x0a, 0x01,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x72, 0x32, 0x3e, 0x0a, 0x04, 0x54, 0x72,
	0x69, 0x6d, 0x12, 0x36, 0x0a, 0x09, 0x54, 0x72, 0x69, 0x6d, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x69, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x69, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x6b, 0x0a, 0x0a, 0x41, 0x64,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x03, 0x53, 0x75, 0x6d, 0x12,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x63, 0x61, 0x74,
	0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trim_trim_proto_rawDescOnce sync.Once
	file_trim_trim_proto_rawDescData = file_trim_trim_proto_rawDesc
)

func file_trim_trim_proto_rawDescGZIP() []byte {
	file_trim_trim_proto_rawDescOnce.Do(func() {
		file_trim_trim_proto_rawDescData = protoimpl.X.CompressGZIP(file_trim_trim_proto_rawDescData)
	})
	return file_trim_trim_proto_rawDescData
}

var file_trim_trim_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_trim_trim_proto_goTypes = []any{
	(*TrimRequest)(nil),  // 0: proto.TrimRequest
	(*TrimResponse)(nil), // 1: proto.TrimResponse
	(*StrRequest)(nil),   // 2: proto.StrRequest
	(*StrResponse)(nil),  // 3: proto.StrResponse
}
var file_trim_trim_proto_depIdxs = []int32{
	0, // 0: proto.Trim.TrimSpace:input_type -> proto.TrimRequest
	2, // 1: proto.AddService.Sum:input_type -> proto.StrRequest
	2, // 2: proto.AddService.Concat:input_type -> proto.StrRequest
	1, // 3: proto.Trim.TrimSpace:output_type -> proto.TrimResponse
	3, // 4: proto.AddService.Sum:output_type -> proto.StrResponse
	3, // 5: proto.AddService.Concat:output_type -> proto.StrResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trim_trim_proto_init() }
func file_trim_trim_proto_init() {
	if File_trim_trim_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trim_trim_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TrimRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trim_trim_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TrimResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trim_trim_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*StrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trim_trim_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*StrResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trim_trim_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_trim_trim_proto_goTypes,
		DependencyIndexes: file_trim_trim_proto_depIdxs,
		MessageInfos:      file_trim_trim_proto_msgTypes,
	}.Build()
	File_trim_trim_proto = out.File
	file_trim_trim_proto_rawDesc = nil
	file_trim_trim_proto_goTypes = nil
	file_trim_trim_proto_depIdxs = nil
}
